---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Restic Rest Server
  category: ${CLUSTER_TITLE}
  description: Restic Backup Server for being a restic source
  url: &url https://restic.${CLUSTER_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/restic.svg
  access_policy:
    groups:
      - admins
  gatus:
    - group: "System"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
