NUT_SERVERS:
  - HOST: alpha-site-host
    PORT: 3493
    USERNAME: "op://Eris/Network UPS Tools/username"
    PASSWORD: "op://Eris/Network UPS Tools/password"
DATE_FORMAT: MM/DD/YYYY
TIME_FORMAT: 12-hour
DASHBOARD_SECTIONS:
  - key: KPIS
    enabled: true
  - key: CHARTS
    enabled: true
  - key: VARIABLES
    enabled: true
DISABLE_VERSION_CHECK: false
