services:
  zot:
    image: ghcr.io/project-zot/zot:v2.1.13@sha256:d3cde44fa759bf7f3d25b479e2b33ed5d4d3f1d6fdad01b204d15a9c3af2db3c
    ports:
      - 6785:6785
    restart: unless-stopped
    dns:
      - 100.100.100.100
    labels:
      # Enable Traefik
      traefik.enable: true

      # Zot Registry - HTTPS
      traefik.http.routers.registry.rule: Host(`registry.${searchDomain}`)
      traefik.http.routers.registry.entrypoints: websecure
      traefik.http.routers.registry.tls.certresolver: le
      traefik.http.routers.registry.service: registry

      traefik.http.routers.registry-tailscale.rule: Host(`registry.${tailscaleDomain}`)
      traefik.http.routers.registry-tailscale.entrypoints: tailscale
      traefik.http.routers.registry-tailscale.service: registry

      traefik.http.services.registry.loadbalancer.server.port: 6785
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ./config/config.json:/etc/zot/config.json
      - ./config/credentials.json:/etc/credentials/credentials.json
      - ./data:/var/lib/registry
    networks:
      - dockge_default
networks:
  dockge_default:
    external: true
x-dockge:
  urls:
    - https://registry.${searchDomain}
    - https://registry.${tailscaleDomain}
