services:
  zot:
    image: ghcr.io/project-zot/zot:v2.1.11@sha256:3173a595c5bbb62dcce0bc13c6d86d4dbfbaae3167fb0dacc79d0b50eb494783
    ports:
      - 6785:6785
    restart: unless-stopped
    dns:
      - 100.100.100.100
    labels:
      # Enable Traefik
      traefik.enable: true

      # Zot Registry - HTTPS
      traefik.http.routers.registry.rule: Host(`registry.${searchDomain}`)
      traefik.http.routers.registry.entrypoints: websecure
      traefik.http.routers.registry.tls.certresolver: le
      traefik.http.routers.registry.service: registry

      traefik.http.routers.registry-tailscale.rule: Host(`registry.${tailscaleDomain}`)
      traefik.http.routers.registry-tailscale.entrypoints: tailscale
      traefik.http.routers.registry-tailscale.service: registry

      traefik.http.services.registry.loadbalancer.server.port: 6785
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ./config/config.json:/etc/zot/config.json
      - ./config/credentials.json:/etc/credentials/credentials.json
      - ./data:/var/lib/registry
    networks:
      - dockge_default
networks:
  dockge_default:
    external: true
x-dockge:
  urls:
    - https://registry.${searchDomain}
    - https://registry.${tailscaleDomain}
