services:
  peanut:
    image: brandawg93/peanut:5.19.2@sha256:feef67c1b97376593dbf2dee800349df97b62b7daf961d3531483c84f289445e
    container_name: PeaNUT
    restart: unless-stopped
    dns:
      - 100.100.100.100
    volumes:
      - ./config:/config
    environment:
      WEB_PORT: 8909
    labels:
      # Enable Traefik
      traefik.enable: true

      traefik.http.routers.peanut.rule: Host(`${APP}.${searchDomain}`)
      traefik.http.routers.peanut.middlewares: authentik-outpost@docker
      traefik.http.routers.peanut.entrypoints: websecure
      traefik.http.routers.peanut.tls.certresolver: le
      traefik.http.routers.peanut.service: peanut

      traefik.http.routers.peanut-tailscale.rule: Host(`peanut.${tailscaleDomain}`)
      traefik.http.routers.peanut-tailscale.entrypoints: tailscale
      traefik.http.routers.peanut-tailscale.service: peanut

      traefik.http.services.peanut.loadbalancer.server.port: 8909
    networks:
      - dockge_default
x-dockge:
  urls:
    - https://${APP}.${searchDomain}
    - https://peanut.${tailscaleDomain}
networks:
  dockge_default:
    external: true
