services:
  peanut:
    image: brandawg93/peanut:5.16.0@sha256:5a067c06814b193180c4e2487c2454f598702984c9f7fa6e1d2ffc8300ce0ed0
    container_name: PeaNUT
    restart: unless-stopped
    dns:
      - 100.100.100.100
    volumes:
      - ./config:/config
    environment:
      WEB_PORT: 8909
    labels:
      tsdproxy.enable: false
      tsdproxy.ephemeral: true
      tsdproxy.name: ${APP}-${CLUSTER_KEY}

      # Enable Traefik
      traefik.enable: true

      traefik.http.routers.peanut.rule: Host(`${APP}.${searchDomain}`)
      traefik.http.routers.peanut.middlewares: authentik-outpost@docker
      traefik.http.routers.peanut.entrypoints: websecure
      traefik.http.routers.peanut.tls.certresolver: le
      traefik.http.routers.peanut.service: peanut
      traefik.http.services.peanut.loadbalancer.server.port: 8909
    networks:
      - dockge_default
x-dockge:
  urls:
    - https://${APP}.${searchDomain}
networks:
  dockge_default:
    external: true
