services:
  uptime:
    container_name: uptime
    image: ghcr.io/twin/gatus:v5.33.1@sha256:7121b5916c069eac6e266875d4984ec9262d84bd1274963939b358b32476d25b
    restart: unless-stopped
    dns:
      - 100.100.100.100
    environment:
      GATUS_CONFIG_PATH: /config
    labels:
      # Enable Traefik
      traefik.enable: true

      traefik.http.routers.uptime.rule: Host(`uptime.${searchDomain}`)
      traefik.http.routers.uptime.entrypoints: websecure
      traefik.http.routers.uptime.service: uptime
      traefik.http.routers.uptime.tls.certresolver: le

      traefik.http.routers.uptime-tailscale.rule: Host(`uptime.${tailscaleDomain}`)
      traefik.http.routers.uptime-tailscale.entrypoints: tailscale
      traefik.http.routers.uptime-tailscale.service: uptime

      traefik.http.services.uptime.loadbalancer.server.port: 9595
    volumes:
      - ./config/:/config/
      - ./data/:/data/
    networks:
      - dockge_default
    ports:
      - 9595:9595
x-dockge:
  urls:
    - https://uptime.${searchDomain}
    - https://uptime.${tailscaleDomain}
networks:
  dockge_default:
    external: true
