---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Uptime
  category: Infrastructure
  description: Gatus is an open-source status monitoring service.  This is a overall gatus instance.
  url: &url https://uptime.${searchDomain}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/gatus.svg
  access_policy:
    groups:
      - friends
      - family
  gatus:
    - url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
