---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Duplicati
  category: ${CLUSTER_TITLE}
  description: Duplicati is a self-hosted backup solution.
  url: &url https://duplicati.${CLUSTER_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/duplicati.svg
  access_policy:
    groups:
      - admins
  authentik:
    proxy:
      mode: "forward_single"
      externalHost: *url
  gatus:
    - group: "System"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
