services:
  nut-exporter:
    container_name: nut-exporter
    image: hon95/prometheus-nut-exporter:1.2.1@sha256:a9bfbbae3b12a6486e6e4b933a69a79d01342db27346d6b4cd5512f4eef6b111
    restart: unless-stopped
    environment:
      - NUT_SERVERS=nut@localhost:3493
    ports:
      - "9199:9199"
    labels:
      traefik.enable: false
    networks:
      - dockge_default

  adguard-exporter:
    container_name: adguard-exporter
    image: ebrianne/adguard-exporter:v1.14@sha256:44bb9e0e98f490e7e40c84461a38a59a41e03a21837b70105e048121e7962cb6
    restart: unless-stopped
    environment:
      - ADGUARD_PROTOCOL=http
      - ADGUARD_HOSTNAME=adguard
      - ADGUARD_PORT=3000
      - ADGUARD_USERNAME=${ADGUARD_USERNAME}
      - ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
      - INTERVAL=30s
      - SERVER_PORT=9617
    env_file:
      - path: .env
    ports:
      - "9617:9617"
    labels:
      traefik.enable: false
    networks:
      - dockge_default

networks:
  dockge_default:
    external: true

x-dockge:
  notes: "Alpha-site specific exporters: NUT (UPS) and AdGuard (DNS)"
