# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/gatus.schema.json
storage:
  type: sqlite
  path: /data/data.db

alerting:
  pushover:
    application-token: "op://Eris/Pushover/credential"
    user-key: "op://Eris/Pushover/username"

ui:
  default-sort-by: group
  title: Status | Uptime
  header: Status

web:
  port: 9595
