# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/gatus.schema.json
storage:
  type: sqlite
  path: /data/data.db

alerting:
  pushover:
    application-token: "op://Eris/Gatus Pushover Key/credential"
    user-key: "op://Eris/Gatus Pushover Key/username"
    priority: 1
    resolved-priority: -1
    default-alert:
      type: pushover
      enabled: true
      "send-on-resolved": true
      "failure-threshold": 4
      "success-threshold": 2
      description: "Notify via Pushover"
      send-on-resolved: true

ui:
  default-sort-by: group
  title: Status | Uptime
  header: Status

endpoints:
  - name: External-DNS Helm Repository
    enabled: true
    group: "Flux Helm Repositories"
    url: "https://kubernetes-sigs.github.io/external-dns/index.yaml"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
        enabled: true
        failure-threshold: 3
        success-threshold: 1

web:
  port: 9595
