# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/gatus.schema.json
storage:
  type: sqlite
  path: /data/data.db

concurrency: 2

alerting:
  pushover:
    application-token: "op://Eris/Gatus Pushover Key/credential"
    user-key: "op://Eris/Gatus Pushover Key/username"
    priority: 1
    resolved-priority: -1
    default-alert:
      type: pushover
      enabled: true
      "send-on-resolved": true
      "failure-threshold": 4
      "success-threshold": 2
      description: "Notify via Pushover"

ui:
  default-sort-by: group
  title: Status | Uptime
  header: Status

web:
  port: 9595
