services:

  alloy:
    user: "65534:65534"
    container_name: alloy
    image: grafana/alloy:v1.12.1@sha256:c311595156fca7b1131683d383dae1acfd29e8879d347161d2a6f714ebac0c0b
    restart: unless-stopped
    dns:
      - 100.100.100.100
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy
      - /etc/alloy/config.alloy
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    labels:
      traefik.enable: true
      traefik.http.routers.alloy.rule: Host(`alloy.${CLUSTER_DOMAIN}`)
      traefik.http.routers.alloy.entrypoints: websecure
      traefik.http.routers.alloy.tls.certresolver: le
      traefik.http.services.alloy.loadbalancer.server.port: 12345
      traefik.http.routers.alloy-tailscale.rule: Host(`alloy-${host}.${tailscaleDomain}`)
      traefik.http.routers.alloy-tailscale.entrypoints: tailscale
      traefik.http.routers.alloy-tailscale.service: alloy
    volumes:
      - ./config/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ./data/alloy:/var/lib/alloy:rw
    networks:
      - dockge_default

  prometheus:
    user: "65534:65534"
    container_name: prometheus
    image: prom/prometheus:v3.9.1@sha256:1f0f50f06acaceb0f5670d2c8a658a599affe7b0d8e78b898c1035653849a702
    restart: unless-stopped
    dns:
      - 100.100.100.100
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=2d
      - --storage.tsdb.retention.size=20GB
      - --web.enable-lifecycle
    labels:
      traefik.enable: true
      traefik.http.routers.prometheus.rule: Host(`prometheus.${CLUSTER_DOMAIN}`)
      traefik.http.routers.prometheus.entrypoints: websecure,tailscale
      traefik.http.routers.prometheus.tls.certresolver: le
      traefik.http.routers.prometheus.service: prometheus
      traefik.http.services.prometheus.loadbalancer.server.port: 9090
      traefik.http.routers.prometheus-tailscale.rule: Host(`prometheus-${host}.${tailscaleDomain}`)
      traefik.http.routers.prometheus-tailscale.entrypoints: tailscale
      traefik.http.routers.prometheus-tailscale.service: prometheus
    volumes:
      - ./data/prometheus:/prometheus:rw
      - ./config/:/etc/prometheus:ro
    networks:
      - dockge_default
    ports:
      - 9090:9090
    depends_on:
      - node-exporter
      - cadvisor
      - blackbox-exporter

  blackbox-exporter:
    user: "65534:65534"
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:v0.28.0@sha256:e753ff9f3fc458d02cca5eddab5a77e1c175eee484a8925ac7d524f04366c2fc
    restart: unless-stopped
    command:
      - --config.file=/config/blackbox.yml
    volumes:
      - ./config/blackbox.yml:/config/blackbox.yml:ro
    labels:
      traefik.enable: false
    networks:
      - dockge_default

  node-exporter:
    user: "65534:65534"
    container_name: node-exporter
    image: prom/node-exporter:v1.10.2@sha256:3ac34ce007accad95afed72149e0d2b927b7e42fd1c866149b945b84737c62c3
    restart: unless-stopped
    command:
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.netclass.ignored-devices=^(veth.*|br.*|docker.*|lo)$$"
      - "--collector.nfs"
      - "--collector.nfsd"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    network_mode: host
    pid: host
    labels:
      traefik.enable: false

  cadvisor:
    user: "65534:65534"
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.55.1@sha256:3de2bd5203120b866d74a9b283b2ffb8ec382fbf9dc321814700c6ea6f44ec57
    restart: unless-stopped
    dns:
      - 100.100.100.100
    privileged: true
    devices:
      - /dev/kmsg
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    labels:
      traefik.enable: false
    networks:
      - dockge_default

x-dockge:
  urls:
    - https://prometheus.${CLUSTER_DOMAIN}
    - https://prometheus-${host}.${tailscaleDomain}
    - https://alloy.${CLUSTER_DOMAIN}
    - https://alloy-${host}.${tailscaleDomain}

networks:
  dockge_default:
    external: true
