services:
  backrest:
    image: garethgeorge/backrest:v1.12.0@sha256:448fee1cb4cdf3f7d7078078480d38713673924ad415bfdf84bf9e49ff570201
    container_name: backrest
    hostname: backrest
    tmpfs: /tmp
    labels:
      # Enable Traefik
      traefik.enable: true

      traefik.http.routers.backrest.rule: Host(`backrest.${CLUSTER_DOMAIN}`)
      traefik.http.routers.backrest.middlewares: authentik-outpost@docker
      traefik.http.routers.backrest.entrypoints: websecure
      traefik.http.routers.backrest.service: backrest
      traefik.http.routers.backrest.tls.certresolver: le

      traefik.http.routers.backrest-tailscale.rule: Host(`backrest-${host}.${tailscaleDomain}`)
      traefik.http.routers.backrest-tailscale.middlewares: authentik-outpost@docker
      traefik.http.routers.backrest-tailscale.entrypoints: tailscale
      traefik.http.routers.backrest-tailscale.service: backrest

      traefik.http.services.backrest.loadbalancer.server.port: 9898
    volumes:
      - ./data:/data
      - ./config:/config
      - ./cache:/cache
      - ./rclone:/root/.config/rclone
      - /data/backup:/backup
      - /data/restic:/repos
      - ./ssh:/root/.ssh:ro
      - spike-backup:/spike/backup:ro
      - spike-data:/spike/data:ro
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=${TIMEZONE}
    networks:
      - dockge_default
    restart: unless-stopped
    dns:
      - 100.100.100.100
networks:
  dockge_default:
    external: true
x-dockge:
  urls:
    - https://backrest.${CLUSTER_DOMAIN}
    - https://backrest-${host}.${tailscaleDomain}
volumes:
  spike-backup:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.10.10.10,rw,nfsvers=4"
      device: ":/mnt/stash/backup/"
  spike-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.10.10.10,rw,nfsvers=4"
      device: ":/mnt/stash/data/"
