---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: Backrest
  category: ${CLUSTER_TITLE}
  description: Backrest is a self-hosted backup UI for Restic repositories and schedules.
  url: &url https://backrest.${CLUSTER_DOMAIN}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/backrest.svg
  access_policy:
    groups:
      - admins
  # authentik:
  #   proxy:
  #     mode: "forward_single"
  #     externalHost: *url
  gatus:
    - url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
