
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: postgresus
spec:
  name: Postgresus
  category: Infrastructure
  url: &url https://postgresus.${searchDomain}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/postgresus.svg
  access_policy:
    groups:
      - admins
  gatus:
  - url: *url
    method: GET
    enabled: false
    client:
      insecure: true
    group: "AdGuard Home"
    conditions:
      - "[STATUS] == 200"

