---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-sync
  namespace: obsidian-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: obsidian-sync-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        couchdb-user: "{{ .couchdbUser }}"
        couchdb-password: "{{ .couchdbPassword }}"
  dataFrom:
    - extract:
        key: obsidian-sync
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-sync-tailscale-auth
  namespace: obsidian-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: obsidian-sync-tailscale-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        authkey: "{{ .tailscaleAuthKey }}"
  dataFrom:
    - extract:
        key: tailscale-auth-keys
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-sync-restic
  namespace: obsidian-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: obsidian-sync-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .resticRepository }}"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .awsAccessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .awsSecretAccessKey }}"
  dataFrom:
    - extract:
        key: volsync-restic-config
