---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obsidian-sync
resources:
  - ./namespace.yaml
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./volsync.yaml
  - ./post-install-hook.yaml
  - ./applicationdefinition.yaml
