
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: zigbee
spec:
  name: Zigbee
  category: Applications
  url: &url https://zigbee.${searchDomain}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/zigbee2mqtt.svg
  access_policy:
    groups:
      - admins
  gatus:
    - url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
