# Thanos object storage configuration
# This file uses env var substitution from docker-compose
type: S3
config:
  bucket: "op://Eris/Thanos S3 Storage/bucket"
  endpoint: "op://Eris/Thanos S3 Storage/endpoint"
  access_key: "op://Eris/Thanos S3 Storage/username"
  secret_key: "op://Eris/Thanos S3 Storage/password"
  insecure: true
  signature_version2: false
  http_config:
    idle_conn_timeout: 90s
    response_header_timeout: 2m
    insecure_skip_verify: false
